version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: listingspw
      MYSQL_DATABASE: 'listings_db'
    ports:
      - '3307:3307'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8090:8080'