GET http://localhost:5030/health

###

GET http://localhost:5030/api/listings

###

POST http://localhost:5030/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"name": "Mariskooli3",
"price": 70.99,
"description": "Punainen mariskooli",
"image": "https://images.stockmann.com/products/a002149684516129274055d229837ab49685e0be/550x734/112356910_1.jpg"

}

###

PUT http://localhost:5030/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"id": 8,
"name": "Muumimuki",
"price": 30.99,
"description": "Harvinainen kerailyesine",
"image": "https://finmug.fi/cdn/shop/files/Muumimukipiisamirottaluolassa1.webp?v=1707208560"

}

###

POST http://localhost:5030/api/users/signup 
Content-Type: application/json

{
"name": "Restuser",
"email": "restuser@domain.com",
"password": "password123"
}

###

# @name login

POST http://localhost:5030/api/users/login 
Content-Type: application/json


{
"email": "restuser@domain.com",
"password": "password123"
}

###

GET http://localhost:5030/api/users/currentuser
Content-Type: application/json

###

@authToken = {{login.response.body.token}}