### LOG IN + SIGN UP

POST https://two024-final-project-miikkar7-backend.onrender.com/api/users/signup
Content-Type: application/json

{
"name": "Miikka",
"email": "miikka@domain.com",
"password": "password123"
}

###

# @name login

POST https://two024-final-project-miikkar7-backend.onrender.com/api/users/login
Content-Type: application/json

{
"email": "miikka@domain.com",
"password": "password123"
}

### REFERENCES FOR REQUESTS

@authToken = {{login.response.body.token}}
@listingOwner = {{login.response.body.id}}
@listingName = {{login.response.body.name}}

### GET REQUESTS (HEALTH CHECK, ALL LISTINGS, INDIVIDUAL LISTING, LISTINGS BY OWNER

GET https://two024-final-project-miikkar7-backend.onrender.com/health

###

GET https://two024-final-project-miikkar7-backend.onrender.com/api/listings

###

GET https://two024-final-project-miikkar7-backend.onrender.com/api/listings/1

###

GET https://two024-final-project-miikkar7-backend.onrender.com/api/listings/mylistings/{{listingOwner}}
Authorization: BEARER {{authToken}} 

### POST REQUEST

POST https://two024-final-project-miikkar7-backend.onrender.com/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"name": "Muumimuki",
"price": 29.99,
"description": "Ei niin harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg",
"owner": "{{listingOwner}}",
"displayname": "{{listingName}}"

}

### UPDATE REQUEST

PUT https://two024-final-project-miikkar7-backend.onrender.com/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"id": 1,
"name": "Muumimuki",
"price": 39.99,
"description": "Harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg"

}

### DELETE REQUEST

DELETE https://marketplace-backend-wh8c.onrender.com/api/{{listingOwner}}/1
Authorization: BEARER {{authToken}}

###