### GET ROUTES (VM and Render)

GET http://172.16.4.202:5030/health

###

GET http://172.16.4.202:5030/api/listings

###

GET http://172.16.4.202:5030/api/listings/1

###

GET http://172.16.4.202:5030/api/listings/mylistings/{{listingOwner}}
Authorization: BEARER {{authToken}} 

### Render

GET https://marketplace-backend-wh8c.onrender.com/health

###

GET https://marketplace-backend-wh8c.onrender.com/api/listings

###

GET https://marketplace-backend-wh8c.onrender.com/api/listings/1

###

GET https://marketplace-backend-wh8c.onrender.com/api/listings/mylistings/{{listingOwner}}
Authorization: BEARER {{authToken}} 

###

### POST ROUTE

POST http://172.16.4.202:5030/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"name": "Muumimuki 2",
"price": 29.99,
"description": "Ei niin harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg",
"owner": "{{listingOwner}}",
"displayname": "{{listingName}}"

}

### PUT (UPDATE) ROUTE

PUT http://172.16.4.202:5030/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"id": 2,
"name": "Muumimuki 2",
"price": 49.99,
"description": "Ei niin harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg"

}

### Render

POST https://marketplace-backend-wh8c.onrender.com/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"name": "Muumimuki 2",
"price": 29.99,
"description": "Ei niin harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg",
"owner": "{{listingOwner}}",
"displayname": "{{listingName}}"

}

###

PUT https://marketplace-backend-wh8c.onrender.com/api/listings 
Content-Type: application/json
Authorization: BEARER {{authToken}} 

{

"id": 2,
"name": "Muumimuki 2",
"price": 49.99,
"description": "Ei niin harvinainen muumimuki",
"image": "https://www.sask.fi/wp-content/uploads/2023/12/Muumimuki-haisuli-500px.jpg"

}

###

//SIGN UP + LOG IN -------------------------------------------------------------------------------------------------

POST http://172.16.4.202:5030/api/users/signup 
Content-Type: application/json

{
"name": "Restuser",
"email": "restuser@domain.com",
"password": "password123"
}

###

# @name login

POST http://172.16.4.202:5030/api/users/login 
Content-Type: application/json


{
"email": "restuser@domain.com",
"password": "password123"
}

### Render

POST https://marketplace-backend-wh8c.onrender.com/api/users/signup
Content-Type: application/json

{
"name": "Restuser",
"email": "restuser@domain.com",
"password": "password123"
}

# @name login

POST https://marketplace-backend-wh8c.onrender.com/api/users/login
Content-Type: application/json

{
"email": "restuser@domain.com",
"password": "password123"
}

###

@authToken = {{login.response.body.token}}
@listingOwner = {{login.response.body.id}}
@listingName = {{login.response.body.name}}