name: Deployment
on:
  # Triggers the workflow on push events to the "main" branch
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: tite-5g00ev16-3003/finalproject-miikkar7-frontend
  BACKEND_IMAGE_NAME: tite-5g00ev16-3003/finalproject-miikkar7-backend

jobs:
  build:
    # Name of Job
    name: Build Container Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fetch code
        uses: actions/checkout@v4.1.1

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18"
      - name: Set up QEmu
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #Backend
      - name: Build and Push the Backend Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}"


      - name: Create production .env file from secret
        run: echo "${{ secrets.ENV_FILE_PROD }}" > ./frontend/.env

      
      - name: Build the Frontend Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}"

  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to Render
        env:
          deploy_url: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          curl "$deploy_url"

      - name: Deploy backend to Render
        env: 
          deploy_url: ${{ secrets.RENDER_BACKEND_HOOK }}
        run: |
          curl "$deploy_url"

  vm-deploy: 
    name: Server Deployment
    timeout-minutes: 5
    runs-on: ubuntu-latest

    needs: build
  
    permissions:
      contents: read
      packages: write

    steps:
      - name: Fetch code
        uses: actions/checkout@v4.1.1

      - name: Install OpenVPN and RSync
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt --assume-yes --no-install-recommends install openvpn openvpn-systemd-resolved rsync

      - name: Setup the VPN configs
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > config.ovpn
          echo "${{ secrets.VPN_PASSWORD }}" > secret.txt

      - name: Connect VPN
        run: sudo openvpn --config config.ovpn --daemon --log vpn.log

      - name: Wait for VPN connection
        timeout-minutes: 1
        run: until ping -c1 ${{ secrets.REMOTE_SERVER }}; do sleep 10; done

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.DEPLOY_KEY_PRIVATE }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts

      
      - name: Create and sync stack configuration
        run: |
          mkdir -p finalproject
          cp docker-compose.server.yml finalproject/docker-compose.yml
          mkdir -p finalproject/db
          cp db/init.prod.sql finalproject/db
          echo "${{ secrets.ENV_FILE_PROD }}" > finalproject/.env
          echo "BACKEND_IMAGE=${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}" >> finalproject/.env
          echo "FRONTEND_IMAGE=${{ env.REGISTRY}}/${{ env.FRONTEND_IMAGE_NAME }}" >> finalproject/.env
          rsync -r finalproject "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }}:./"
      
      - name: Start containers via SSH
        run:
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_SERVER }} 
          "
          docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }};
          cd finalproject;
          docker-compose pull;
          docker-compose up -d;
          "


      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn