name: CI/CD
#test change
on:
  push:
    branches-ignore:
      - "main"

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: tite-5g00ev16-3003/finalproject-miikkar7-frontend
  BACKEND_IMAGE_NAME: tite-5g00ev16-3003/finalproject-miikkar7-backend

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Fetch code
        uses: actions/checkout@v4.1.1

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "18"

      - name: Install MySQL server
        uses: shogo82148/actions-setup-mysql@v1.31.0
        with:
          mysql-version: "8.0"
          auto-start: true

      - name: Configure the MySQL server
        run:  |
          mysql -u root -h 127.0.0.1 -e 'SELECT version()'
          mysql -h 127.0.0.1 -P 3306 -u root -e 'CREATE DATABASE test_db;'
          mysql -h 127.0.0.1 -P 3306 -u root -e 'SHOW DATABASES;'
          mysql -h 127.0.0.1 -P 3306 -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"
          mysql -h 127.0.0.1 -P 3306 -u root -e 'FLUSH PRIVILEGES' -ppassword

      - name: Seed the database
        working-directory: ./db
        run: mysql -h 127.0.0.1 -P3306 -u root -ppassword test_db < init.sql

      - name: Create testing .env file from secret
        run: |
          echo "${{ secrets.TEST_JOB_ENV }}" > ./backend/.env

      - name: Install the backend deps
        working-directory: ./backend
        run: npm install --force

      # Run backend tests
      - name: Run the backend tests
        working-directory: ./backend
        run: npm run test

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install


      # Run frontend tests
      #- name: Run the frontend tests
      #  working-directory: ./frontend
      #  run: npm run test:cypress

      #- name: Run the frontend tests
        #working-directory: ./frontend
        #run:  |
          #cd ..
          #cd backend
          #npm run dev & sleep 10 && curl http://localhost:5000/api/menuitems/1 &
          #cd ..
          #cd frontend
          #npm run dev & sleep 10 && curl http://localhost:5173 &
          #npm run test:cypress

  build:
    runs-on: ubuntu-latest

    needs: test

    permissions:
      contents: read
      packages: write

    steps:
      - name: Fetch code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Set up QEmu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #Backend
      - name: Build and Push the Backend Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: "${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}"

      # Frontend
      - name: Build the Frontend Image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: "${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}"